"""WikiMemory data model for persistent agent memory during wiki generation.

This module defines the WikiMemory Beanie document for storing memories
generated by wiki agents during repository analysis and documentation generation.
Memories are used for cross-referencing, pattern recognition, and maintaining
structural decisions across agent runs.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List
from uuid import UUID

from pydantic import Field
from pymongo import ASCENDING, IndexModel

from .base import BaseDocument


class MemoryType(str, Enum):
    """Types of memories that wiki agents can create.

    - structural_decision: Decisions about wiki structure and organization
    - pattern_found: Patterns discovered in the codebase (naming, architecture, etc.)
    - cross_reference: Links and relationships between different parts of the codebase
    """

    structural_decision = "structural_decision"
    pattern_found = "pattern_found"
    cross_reference = "cross_reference"


class WikiMemory(BaseDocument):
    """WikiMemory model for persistent agent memory during wiki generation.

    Stores memories created by wiki agents (structure_agent, page_agent) during
    repository analysis. These memories help maintain consistency across pages,
    track discovered patterns, and preserve structural decisions.
    """

    # Core identification
    repository_id: UUID = Field(description="Foreign key to Repository")
    memory_type: MemoryType = Field(description="Type of memory")

    # Content
    content: str = Field(
        description="Memory content", max_length=4000
    )

    # Vector embedding for semantic search
    embedding: List[float] = Field(
        default_factory=list,
        description="Vector embedding (384 dimensions)",
    )

    # Source tracking
    source_agent: str = Field(
        description="Agent identifier ('structure_agent' or 'page_agent')"
    )

    # Related entities
    file_paths: List[str] = Field(
        default_factory=list,
        description="Related file paths in the repository",
    )
    related_pages: List[str] = Field(
        default_factory=list,
        description="Related wiki page identifiers",
    )

    # Metadata
    embedding_metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata about the embedding (model, timestamp, etc.)",
    )

    # Audit fields
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last update timestamp",
    )

    class Settings:
        name = "wiki_memories"
        indexes = [
            # Index on repository_id for filtering memories by repository
            IndexModel("repository_id"),
            # Compound index on (repository_id, memory_type) for filtering by type
            IndexModel([("repository_id", ASCENDING), ("memory_type", ASCENDING)]),
            # Index on (repository_id, file_paths) for finding memories by file
            IndexModel([("repository_id", ASCENDING), ("file_paths", ASCENDING)]),
        ]
